# Generated by Django 4.2.4 on 2023-08-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
